#!/usr/bin/env bash
# ifinmail provision.sh - one-command production provisioning.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROVISIONING_DIR="$(dirname "$SCRIPT_DIR")"
DOCKER_DIR="$PROVISIONING_DIR/docker"
ENV_FILE="$PROVISIONING_DIR/.env"
DOMAIN="${DOMAIN:-ifinsta.online}"
MAIL_DOMAIN="${MAIL_DOMAIN:-$DOMAIN}"
MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.$DOMAIN}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@$DOMAIN}"
DKIM_SELECTOR="${DKIM_SELECTOR:-default}"
COMPOSE=()
LEGACY_COMPOSE=false

die() {
    echo "ERROR: $*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "$1 is required"
}

detect_compose() {
    if docker compose version >/dev/null 2>&1; then
        COMPOSE=(docker compose --env-file "$ENV_FILE" -f "$DOCKER_DIR/docker-compose.yml")
    elif command -v docker-compose >/dev/null 2>&1; then
        COMPOSE=(docker-compose --env-file "$ENV_FILE" -f "$DOCKER_DIR/docker-compose.yml")
        LEGACY_COMPOSE=true
    else
        die "docker compose v2 or docker-compose v1 is required"
    fi
}

rand_b64() {
    openssl rand -base64 "$1" | tr -d '\n'
}

ensure_env() {
    if [ -f "$ENV_FILE" ]; then
        set -a
        # shellcheck disable=SC1090
        source "$ENV_FILE"
        set +a

        DOMAIN="${DOMAIN:-ifinsta.online}"
        MAIL_DOMAIN="${MAIL_DOMAIN:-$DOMAIN}"
        MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.$DOMAIN}"
        ADMIN_EMAIL="${ADMIN_EMAIL:-admin@$DOMAIN}"
        DKIM_SELECTOR="${DKIM_SELECTOR:-default}"

        grep -q '^MAIL_DOMAIN=' "$ENV_FILE" || echo "MAIL_DOMAIN=$MAIL_DOMAIN" >> "$ENV_FILE"
        grep -q '^MAIL_HOSTNAME=' "$ENV_FILE" || echo "MAIL_HOSTNAME=$MAIL_HOSTNAME" >> "$ENV_FILE"
        grep -q '^ADMIN_EMAIL=' "$ENV_FILE" || echo "ADMIN_EMAIL=$ADMIN_EMAIL" >> "$ENV_FILE"
        grep -q '^DKIM_SELECTOR=' "$ENV_FILE" || echo "DKIM_SELECTOR=$DKIM_SELECTOR" >> "$ENV_FILE"
        return
    fi

    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by provisioning/scripts/provision.sh
DOMAIN=$DOMAIN
MAIL_DOMAIN=$MAIL_DOMAIN
MAIL_HOSTNAME=$MAIL_HOSTNAME
ADMIN_EMAIL=$ADMIN_EMAIL

COREDNS_IP=127.0.0.1

POSTGRES_ADMIN_PASSWORD=$(rand_b64 36)
DOVECOT_DB_PASSWORD=$(rand_b64 36)
POSTFIX_DB_PASSWORD=$(rand_b64 36)

SECRET_KEY=$(rand_b64 48)
DJANGO_ALLOWED_HOSTS=$DOMAIN,$MAIL_HOSTNAME

REDIS_HOST=redis
REDIS_PORT=6379

DKIM_SELECTOR=$DKIM_SELECTOR

BACKUP_RETENTION_DAYS=30
BACKUP_ENCRYPT=false

MONITOR_QUEUE_WARN=50
MONITOR_QUEUE_CRITICAL=200
MONITOR_CERT_WARN_DAYS=30
MONITOR_CERT_CRITICAL_DAYS=7
EOF

    echo "Created production environment: $ENV_FILE"
}

validate_env() {
    local required=(
        DOMAIN
        MAIL_DOMAIN
        MAIL_HOSTNAME
        ADMIN_EMAIL
        POSTGRES_ADMIN_PASSWORD
        DOVECOT_DB_PASSWORD
        POSTFIX_DB_PASSWORD
        SECRET_KEY
    )
    local missing=false

    for name in "${required[@]}"; do
        local value="${!name:-}"
        if [ -z "$value" ] || [[ "$value" == change_me* ]] || [[ "$value" == dev_* ]] || [[ "$value" == *example.com* ]]; then
            echo "  $name is missing or still uses a placeholder"
            missing=true
        fi
    done

    [ "$missing" = false ] || die "update $ENV_FILE and rerun make provision"
}

ensure_directories() {
    mkdir -p "$DOCKER_DIR/certs/live/$MAIL_HOSTNAME" "$DOCKER_DIR/nginx/www" "$DOCKER_DIR/dkim"
}

ensure_bootstrap_cert() {
    local cert_dir="$DOCKER_DIR/certs/live/$MAIL_HOSTNAME"
    local cert="$cert_dir/fullchain.pem"
    local key="$cert_dir/privkey.pem"
    local dh="$cert_dir/dh.pem"

    mkdir -p "$cert_dir"

    if [ ! -s "$cert" ] || [ ! -s "$key" ]; then
        echo "Creating bootstrap self-signed TLS certificate for $MAIL_HOSTNAME..."
        openssl req -x509 -nodes -newkey rsa:2048 -days 7 \
            -subj "/CN=$MAIL_HOSTNAME" \
            -addext "subjectAltName=DNS:$DOMAIN,DNS:$MAIL_HOSTNAME" \
            -keyout "$key" \
            -out "$cert" >/dev/null 2>&1
        chmod 600 "$key"
    fi

    if [ ! -s "$dh" ]; then
        echo "Generating Dovecot DH parameters..."
        openssl dhparam -out "$dh" 2048 >/dev/null 2>&1
    fi
}

ensure_dkim() {
    local key_path="$DOCKER_DIR/dkim/$DKIM_SELECTOR.$DOMAIN.key"
    local pub_path="${key_path%.key}.pub"

    if [ ! -s "$key_path" ]; then
        echo "Generating DKIM key for $DKIM_SELECTOR._domainkey.$DOMAIN..."
        openssl genrsa -out "$key_path" 2048 >/dev/null 2>&1
        openssl rsa -in "$key_path" -pubout -out "$pub_path" >/dev/null 2>&1
        chmod 600 "$key_path"
    fi

    cat > "$DOCKER_DIR/rspamd/local.d/dkim_signing.conf" <<EOF
allow_username_mismatch = true;
sign_local = true;
use_esld = false;
try_fallback = true;

domain {
  $DOMAIN {
    selector = "$DKIM_SELECTOR";
    path = "/etc/dkim/$DKIM_SELECTOR.$DOMAIN.key";
  }
}
EOF
}

obtain_certificate() {
    local live_dir="$DOCKER_DIR/certs/live/$MAIL_HOSTNAME"
    local issuer

    issuer="$(openssl x509 -in "$live_dir/fullchain.pem" -noout -issuer 2>/dev/null || true)"
    if [[ "$issuer" != *"Let's Encrypt"* ]]; then
        echo "Attempting Let's Encrypt certificate for $DOMAIN and $MAIL_HOSTNAME..."
        if "$SCRIPT_DIR/obtain-ssl.sh"; then
            return
        fi

        echo "WARNING: Let's Encrypt issuance failed. The stack is running with a temporary self-signed certificate."
        echo "         Fix DNS/firewall for $DOMAIN and $MAIL_HOSTNAME, then rerun: make provision"
        ensure_bootstrap_cert
    else
        echo "Let's Encrypt certificate already present."
    fi
}

print_dns() {
    local pub_path="$DOCKER_DIR/dkim/$DKIM_SELECTOR.$DOMAIN.pub"
    local dkim_value
    dkim_value="$(grep -v '^-' "$pub_path" | tr -d '\n')"

    cat <<EOF

ifinmail is provisioned for $DOMAIN.

DNS records to publish:
  A      $DOMAIN                  <this server IPv4>
  A      $MAIL_HOSTNAME           <this server IPv4>
  MX     $DOMAIN                  10 $MAIL_HOSTNAME.
  TXT    $DOMAIN                  "v=spf1 mx -all"
  TXT    _dmarc.$DOMAIN           "v=DMARC1; p=quarantine; rua=mailto:postmaster@$DOMAIN"
  TXT    $DKIM_SELECTOR._domainkey.$DOMAIN "v=DKIM1; k=rsa; p=$dkim_value"

Useful commands:
  make ps
  make logs
  make down
EOF
}

main() {
    echo "======================================"
    echo "  ifinmail production provisioning"
    echo "======================================"

    need_cmd docker
    need_cmd openssl
    detect_compose

    ensure_env
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
    DOMAIN="${DOMAIN:-ifinsta.online}"
    MAIL_DOMAIN="${MAIL_DOMAIN:-$DOMAIN}"
    MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.$DOMAIN}"
    ADMIN_EMAIL="${ADMIN_EMAIL:-admin@$DOMAIN}"
    DKIM_SELECTOR="${DKIM_SELECTOR:-default}"
    validate_env

    ensure_directories
    ensure_bootstrap_cert
    ensure_dkim

    echo "Building images..."
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" build --pull)

    if [ "$LEGACY_COMPOSE" = true ]; then
        (cd "$DOCKER_DIR" && "${COMPOSE[@]}" rm -fs api postfix dovecot rspamd >/dev/null 2>&1 || true)
    fi

    echo "Starting stack..."
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" up -d)

    obtain_certificate
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" restart postfix dovecot nginx)

    echo "Current service status:"
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" ps)

    print_dns
}

main "$@"
