# Dovecot 90-sieve.conf — Sieve filtering for ifinmail
plugin {
  sieve = file:~/sieve;active=~/.dovecot.sieve
  sieve_before = /etc/dovecot/sieve/before.d/
  sieve_after = /etc/dovecot/sieve/after.d/
  sieve_max_script_size = 1M
  sieve_max_actions = 32
  sieve_quota_max_scripts = 4
}

protocol lmtp {
  mail_plugins = $mail_plugins sieve
}

protocol imap {
  mail_plugins = $mail_plugins imap_sieve
}
