# ifinmail Dovecot main configuration
protocols = imap lmtp

# Include modular config files
!include conf.d/*.conf

# Base directory for runtime files
base_dir = /var/run/dovecot/

# Instance name
instance_name = ifinmail

# Login access
login_greeting = ifinmail ready.
login_log_format_elements = user=<%u> method=%m rip=%r lip=%l mpid=%e %c
