allow_username_mismatch = true;
sign_local = true;
use_esld = false;
try_fallback = true;

domain {
  ifinsta.online {
    selector = "default";
    path = "/etc/dkim/default.ifinsta.online.key";
  }
}
